### ISSUE TITLE
cant send messages ingame to discord

### ISSUE THREAD

**Issue by Varkest** [xradiusa/Interweave#19]
Hello there!
I really like this mod!, I just seem to have a slight problem sending messages 
from in-game to discord.
I am getting the following error when I type a message in game: 

Uncaught exception in thread "Interweave"
java.lang.ClassCastException: class net.minecraft.class_7417$1 cannot be cast to class net.minecraft.class_2585 (net.minecraft.class_7417$1 and net.minecraft.class_2585 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @dfd3711)
	at main.Interweave.lambda$sendMessage$4(Interweave.java:165) ~[interweave-1.0.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	
The server is running the latest Fabric-API 0.56.0 for Minecraft 1.19
Its neither crashing nor preventing other functions of the interweave mod, I can send messages from discord to minecraft without a problem, as well as receive start/stop join/leave messages on discord.

If theres any way I can showcase this problem to you better please let me know!

**Comment by xradiusa** [comment]
I don't seem to be able to recreate this, could you send me your mod list and your interweaveConfig.json? (Make sure to redact the discordToken and channelID).

**Comment by Varkest** [comment]
Yes!

heres the interweaveConfig.json:
![Unbenannt](https://user-images.githubusercontent.com/107756997/174447711-97fe8a85-dca0-4fd8-a940-09e7ca46f20a.PNG)

and heres the mod-list with all what we currently use: (might be worth noting that I extracted it from the "latest" log, I hope this isnt too cluttered, if not I'll send in just the normal mod-list)

![1](https://user-images.githubusercontent.com/107756997/174447910-789beab4-f9a3-4f72-ab95-adbe6efb0a12.PNG)
![2](https://user-images.githubusercontent.com/107756997/174447933-90d02a2a-9e4e-42c1-b83a-5b4205df3859.PNG)
![3](https://user-images.githubusercontent.com/107756997/174447920-94b4e703-1d37-4d26-a7ea-8c35cdd3b8be.PNG)


This is my first time really interacting on github so I hope I'm not being too much!
thanks a lot!
